name: copy-changes-from-file-A-to-file-B
run-name: ${{ github.actor }} moved changes from file A to file B
on: [ push ]
jobs:
  copy-files-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cp /src/main/kotlin/config/file_A.json /src/main/kotlin/config/file_B.json
